language: python
sudo: false

python:
  - 3.5
  - 3.6

install:
  - curl https://sh.rustup.rs -sSf > rustup-init.sh
  - sh rustup-init.sh --default-toolchain nightly -y -v
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustc --version
  - pip install pipenv
  - make install
  - pipenv graph

script:
  - export PATH="$HOME/.cargo/bin:$PATH"
  - make test
  - make bench-compare
